import { Fighter } from './types';

export const UFC_FIGHTERS: Record<string, Fighter> = {
  'islam-makhachev': {
    name: 'Ислам Махачев',
    wins: 26,
    losses: 1,
    draws: 0,
    strikeAccuracy: 52,
    takedownAccuracy: 58,
    submissionRate: 62,
    koRate: 23,
    age: 33,
    reach: 178,
    weight: 70
  },
  'alex-volkanovski': {
    name: 'Александр Волкановски',
    wins: 26,
    losses: 3,
    draws: 0,
    strikeAccuracy: 56,
    takedownAccuracy: 45,
    submissionRate: 15,
    koRate: 42,
    age: 35,
    reach: 168,
    weight: 66
  },
  'jon-jones': {
    name: 'Джон Джонс',
    wins: 27,
    losses: 1,
    draws: 0,
    strikeAccuracy: 52,
    takedownAccuracy: 43,
    submissionRate: 33,
    koRate: 33,
    age: 37,
    reach: 215,
    weight: 108
  },
  'alexander-pereira': {
    name: 'Алекс Перейра',
    wins: 11,
    losses: 2,
    draws: 0,
    strikeAccuracy: 58,
    takedownAccuracy: 0,
    submissionRate: 0,
    koRate: 82,
    age: 37,
    reach: 201,
    weight: 93
  },
  'sean-omalley': {
    name: 'Шон О\'Мэлли',
    wins: 18,
    losses: 1,
    draws: 1,
    strikeAccuracy: 54,
    takedownAccuracy: 20,
    submissionRate: 17,
    koRate: 61,
    age: 30,
    reach: 183,
    weight: 61
  },
  'dricus-du-plessis': {
    name: 'Дрикус Дю Плесси',
    wins: 21,
    losses: 2,
    draws: 0,
    strikeAccuracy: 48,
    takedownAccuracy: 55,
    submissionRate: 38,
    koRate: 38,
    age: 30,
    reach: 193,
    weight: 84
  },
  'ilia-topuria': {
    name: 'Илия Топурия',
    wins: 15,
    losses: 0,
    draws: 0,
    strikeAccuracy: 60,
    takedownAccuracy: 75,
    submissionRate: 33,
    koRate: 53,
    age: 27,
    reach: 175,
    weight: 66
  },
  'tom-aspinall': {
    name: 'Том Аспинал',
    wins: 15,
    losses: 3,
    draws: 0,
    strikeAccuracy: 56,
    takedownAccuracy: 62,
    submissionRate: 47,
    koRate: 60,
    age: 31,
    reach: 200,
    weight: 115
  },
  'belal-muhammad': {
    name: 'Белал Мухаммад',
    wins: 24,
    losses: 3,
    draws: 1,
    strikeAccuracy: 46,
    takedownAccuracy: 49,
    submissionRate: 13,
    koRate: 25,
    age: 36,
    reach: 183,
    weight: 77
  },
  'merab-dvalishvili': {
    name: 'Мераб Двалишвили',
    wins: 17,
    losses: 4,
    draws: 0,
    strikeAccuracy: 43,
    takedownAccuracy: 55,
    submissionRate: 18,
    koRate: 6,
    age: 34,
    reach: 173,
    weight: 61
  }
};
